version: "3.7"
services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:32
    restart: unless-stopped
    depends_on:
      - nextcloud-db
    environment:
      - TZ=${TZ}
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - REDIS_HOST=shared_valkey
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_AUTHTYPE=${SMTP_AUTHTYPE}
      - SMTP_NAME=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASS}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.jeya.dev
    volumes:
      - ${NEXTCLOUD_APP_LOCATION}:/var/www/html
      - ${NEXTCLOUD_DATA_LOCATION}:/var/www/html/data
    networks:
      - frontend
      - nextcloud-net
      - valkey-net
    extra_hosts:
      - "cloud.jeya.dev:172.19.0.15"

  nextcloud-db:
    container_name: nextcloud_db
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    networks:
      - nextcloud-net

  nextcloud-cron:
    image: nextcloud:32
    restart: unless-stopped
    container_name: nextcloud_cron
    volumes:
      - ${NEXTCLOUD_APP_LOCATION}:/var/www/html
      - ${NEXTCLOUD_DATA_LOCATION}:/var/www/html/data
    user: www-data
    entrypoint: /bin/sh -c 'while true; do php -f /var/www/html/cron.php; sleep 300; done'
    depends_on:
      - nextcloud
      - nextcloud-db
    networks:
      - nextcloud-net
      - valkey-net

networks:
  frontend:
    external: true
  nextcloud-net:
    name: nextcloud-net
  valkey-net:
    external: true
